apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmed-api
        image: leonardosartorello/vollmed:v9
        ports:
        - containerPort: 3000
        env:
          # Define the environment variable
          - name: DB_HOST # Notice that the case is different here
          # from the key name in the ConfigMap.
            valueFrom:
              configMapKeyRef:
                name: dados           # The ConfigMap this value comes from.
                key: DB_HOST # The key to fetch.
          - name: REDIS_HOST

            valueFrom:
              configMapKeyRef:
                name: dados      
                key: REDIS_HOST 
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: dados
                key: DB_DATABASE

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: senhas
                key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: /paciente
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 3